require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

spec "user.tokyonight"
spec "user.devicons"
spec "user.treesitter"
spec "user.lsp"
spec "user.none-ls"
spec "user.cmp"
spec "user.which-key"
-- spec "user.snap"
spec "user.telescope"
spec "user.trouble"

require "user.lazy"
