_G.lj = {}

vim.loader.enable() -- enable byte-code compilation. also used by lazy

require "base.options"
require "base.lazy"
require "base.keymaps"
require "base.autocmds"

lj.colorscheme = "astrodark"
-- lj.colorscheme = "tokyonight"
-- lj.colorscheme = "tokyodark"
-- lj.colorscheme = "nightfox"
-- lj.colorscheme = "duskfox"
-- lj.colorscheme = "terafox"
-- lj.colorscheme = "nordic"

require "user.spec"

spec "user.colorschemes"
spec "user.devicons"
spec "user.treesitter"
spec "user.lsp"
spec "user.none-ls"
spec "user.cmp"
spec "user.which-key"
spec "user.telescope"
spec "user.trouble"
spec "user.neotree"
spec "user.comment"
spec "user.fidget"
spec "user.neotab"
spec "user.todo-comments"
spec "user.hmts"
-- spec "user.astroline"
spec "user.heirline"
spec "user.grapple"
-- spec "user.staline"
-- spec "user.ufo" -- TODO: see launch.nvim config
spec "user.copilot"
-- spec "user.gitlinker"
spec "user.gitsigns"
-- spec "user.diffview"
spec "user.autopairs"
-- spec "user.lualine"
spec "user.toggleterm"
spec "user.neotest"
spec "user.various-textobjects"
spec "user.smart-splits"
