---
- name: Install core packages
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - build-essential
    - coreutils
    - keychain
    - lz4
    - man-db
    - moreutils
    - p7zip
    - unzip
  become: yes

