---
- name: Add WezTerm GPG key
  ansible.builtin.get_url:
    url: https://apt.fury.io/wez/gpg.key
    dest: /etc/apt/keyrings/wezterm-fury.gpg
    mode: '0644'

- name: Add WezTerm repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *'
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install WezTerm
  ansible.builtin.apt:
    name: wezterm

