---
- include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family in ['Darwin', 'Debian']

- name: Link wezterm config
  file:
    src: "{{ checkout_dir }}/config/wezterm/"
    dest: "{{ ansible_env.HOME }}/.config/wezterm"
    state: link
    force: yes

