#!/bin/bash

set -e

function have {
  command -v "$1" &>/dev/null
}


case "$(uname -s)" in
    Darwin*)
        if ! xcode-select --version 2>/dev/null; then
            xcode-select --install
        fi
        have brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        have ansible || brew install ansible
        ;;
    *)
        have ansible || pip3 install ansible
        ;;
esac

ansible-galaxy install -r requirements.yml
ansible-playbook ansible/playbook.yml
