#+title: Dotfiles
#+author: Jan Laermann
#+date: 2022-06-10

* Dotfiles management

These dotfiles are managed via a /bare/ git repository.
The files live at their original position. No sym-linking, copying, or whatever needed.
Instead, a /bare/ git repository lives at =~/.dotfiles=, with its worktree pointed towards =$HOME=.
Together with a little helper this becomes a really elegant workflow.

** Initialize new dotfiles repo
#+begin_src bash
git init --bare ~/.dotfiles
alias dotfiles="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
dotfiles config --local showUntrackedFiles no

# bash
alias dotfiles="git --git-dir=$HOME/.dotfiles --work-tree=$HOME" >> ~/.bashrc

# zsh
alias dotfiles="git --git-dir=$HOME/.dotfiles --work-tree=$HOME" >> ~/.zshrc

# fish (must be executed in fish)
alias -s dotfiles "git --git-dir=$HOME/.dotfiles --work-tree=$HOME"

dotfiles add ~/.mynewdotfile
dotfiles commit -m "add my new dotfile"
dotfiles status
#+end_src


* Overview

** Terminal Emulator
*** iterm2
When setting up a new system, go to *Preferences* > *General* > *Preferences*, set the path to =~/.config/iterm2/= and change =Save changes at= to =Automatically=.
Under *Preferences* > *Colors* click =Color Presets...= and import all =*.itermcolors= files from the path above.

** Shell
Fish is the main shell, but some basic functionality will also be present in zshand some essentials are also setup in bash.
