---
- name: Add 1Password GPG key
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/keys/1password.asc
    dest: /etc/apt/keyrings/1password-archive-keyring.gpg
    state: present

- name: Add 1Password repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install 1Password
  apt:
    name: 1password
    state: present

