- name: Add fish to /etc/shells
  become: true
  lineinfile:
    path: /etc/shells
    line: /home/linuxbrew/.linuxbrew/bin/fish"
- name: Set fish as default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "/home/linuxbrew/.linuxbrew/bin/fish"
