---
- name: Install fish
  become: "{{ ansible_pkg_mgr != 'brew' }}"
  package:
    name:
      - fish
      - curl

- name: Get the fish binary path
  shell: command -v fish
  register: fish_path
  changed_when: false
  become: false
  environment:
    PATH: "/opt/homebrew//bin:/home/linuxbrew/.linuxbrew/bin:{{ lookup('env', 'PATH') }}"

- name: Add fish to /etc/shells
  become: true
  lineinfile:
    path: /etc/shells
    line: "{{ fish_path.stdout }}"

- name: Set fish as default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish_path.stdout }}"

- name: Install fisher
  # NOTE: fisher update must come first so plugins won't be erased from ~/.config/fish/fish_plugins file
  ansible.builtin.shell: |
    curl -fsSL git.io/fisher | source
    fisher update
    fisher install jorgebucaran/fisher
  args:
    executable: fish
    creates: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
  environment:
    PATH: "/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:{{ lookup('env', 'PATH') }}"
