---
- name: Install fish
  community.general.homebrew:
    name: fish # install via brew on linux so brew completions are automatically added

- name: Get the fish binary path
  shell: PATH=/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:$PATH command -v fish
  register: fish_path
  changed_when: false
  become: false

- name: Add fish to /etc/shells
  become: true
  lineinfile:
    path: /etc/shells
    line: "{{ fish_path.stdout }}"

- name: Set fish as default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish_path.stdout }}"

- name: Install fisher
  ansible.builtin.shell: |
    curl -fsSL git.io/fisher | source
    fisher install jorgebucaran/fisher
    fisher update
  args:
    executable: "{{ fish_path.stdout }}"
    creates: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
