---
- name: Install fzf
  ansible.builtin.package:
    name: fzf

- name: Ensure fzf is sourced
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    search_string: "fzf --fish | source"
    line: "fzf --fish | source"
