---
- name: Install {{ packages | sort | join(', ')}}
  vars:
    packages:
      - arc
      - slack
      - unar
      - karabiner-elements
      - linearmouse
      - the-unarchiver
      - jetbrains-toolbox
      - podman-desktop
      - monitorcontrol
      - notion-calendar
      - raycast
      - utm
      - libpq
  package:
    name: "{{ packages }}"

- name: Force-link libpq
  command: brew link --force libpq
  args:
    creates: /opt/homebrew/bin/psql
