---
- name: Install {{ packages | sort | join(', ')}}
  become: true
  vars:
    packages:
      - build-essential
      - man-db
      - procps
  package:
    name: "{{ packages }}"
    update_cache: true

- name: Install flatpak
  become: true
  ansible.builtin.apt:
    name: flatpak
    state: present
  when: "'WSL2' not in ansible_facts['kernel']"

- name: Add flathub remote
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present
    method: system
  become: true
  when: "'WSL2' not in ansible_facts['kernel']"

- block:
    - name: Add 1Password GPG key
      ansible.builtin.get_url:
        url: https://downloads.1password.com/linux/keys/1password.asc
        dest: /etc/apt/keyrings/1password-archive-keyring.asc

    - name: Add 1Password repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/1password-archive-keyring.asc] https://downloads.1password.com/linux/debian/amd64 stable main"
        state: present

    - name: Install 1Password
      ansible.builtin.apt:
        name:
          - 1password
          - 1password-cli
        state: present
        update_cache: true
  become: true
  when: ansible_facts['architecture'] == "x86_64"

- block:
    - name: Add Tailscale GPG key
      ansible.builtin.get_url:
        url: "https://pkgs.tailscale.com/stable/{{ ansible_facts['distribution'] | lower }}/{{ ansible_facts['distribution_release'] }}.noarmor.gpg"
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg

    - name: Add Tailscale repository
      ansible.builtin.get_url:
        url: "https://pkgs.tailscale.com/stable/{{ ansible_facts['distribution'] | lower }}/{{ ansible_facts['distribution_release'] }}.tailscale-keyring.list"
        dest: /etc/apt/sources.list.d/tailscale.list

    - name: Install Tailscale
      ansible.builtin.apt:
        name: tailscale
        state: present
        update_cache: true
  become: true
  when: "'WSL2' not in ansible_facts['kernel']"

- name: Install docker engine
  ansible.builtin.shell: curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: true
  become: true

- name: Install zed
  ansible.builtin.shell: curl -fsSL https://zed.dev/install.sh | sh
  args:
    creates: "{{ ansible_facts['env'].HOME }}/.local/bin/zed"
