---
- name: Install {{ packages | sort | join(', ')}}
  become: true
  vars:
    packages:
      - build-essential
      - man-db
      - procps
  package:
    name: "{{ packages }}"
    update_cache: true

- block:
    - name: Add 1Password GPG key
      ansible.builtin.get_url:
        url: https://downloads.1password.com/linux/keys/1password.asc
        dest: /etc/apt/keyrings/1password-archive-keyring.asc

    - name: Add 1Password repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/1password-archive-keyring.asc] https://downloads.1password.com/linux/debian/amd64 stable main"
        state: present

    - name: Install 1Password
      ansible.builtin.apt:
        name:
          - 1password
          - 1password-cli
        state: present
        update_cache: true
  become: true
  when: ansible_architecture == "x86_64"
