- name: Install apt packages
  become: yes
  ansible.builtin.apt:
    name:
      - awscli
      - bat
      - btop
      - curl
      - direnv
      - fd-find
      - ffmpeg
      - fzf
      - git
      - httpie
      - inetutils-tools # telnet, whois, etc
      - jq 
      - lz4 # compression
      - ripgrep
      - p7zip
      - unzip
      - yt-dlp
      - zoxide
      - tealdeer
      
- name: Install Homebrew packages
  import_role:
    name: monolithprojects.homebrew
  become: yes
  vars:
    brew_formulae:
      - doggo
      - eza
      - fish
      - git-delta
      - go
      - lazydocker
      - lazygit
      - neovim
      - rustup # run `rustup-init` after installing
      - starship
