- name: Install Homebrew packages
  community.general.homebrew:
    name:
      - awscli
      - bat
      - btop
      - curl
      - direnv # environment loading on entering a directory
      - doggo # DNS like dig
      - eza # nice ls
      - fd # faster find
      - ffmpeg
      - fish
      - fzf # fuzzy finder
      - git
      - git-delta # fancy diffs
      - go
      - htop
      - httpie # HTTP client
      - hyperfine # benchmarking
      - inetutils # telnet, whois, etc
      - jless # JSON view
      - jo # JSON output
      - jq # JSON manipulator
      - lazydocker
      - lazygit
      - less
      - lz4 # compression
      - neovim
      - p7zip
      - prettyping
      - ripgrep
      - rustup # run `rustup-init` after installing
      - starship
      - tealdeer
      - tree
      - unar
      - unzip
      - uv
      - yt-dlp
      - zoxide

