- name: Check if Homebrew is in PATH
  command: which brew
  register: which_brew
  failed_when: false
  changed_when: false
- debug: msg="{{ which_brew.stdout }}"
- debug: msg="{{ which_brew.stderr }}"
- name: Install Homebrew
  block:
    - name: Ensure sudo access works
      become: yes
      command: /usr/bin/env true
      changed_when: false
    - name: Run Homebrew installer
      shell: |
        /usr/bin/env CI=1 NONINTERACTIVE=1 /bin/bash -c \
        "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        executable: /bin/bash
    - name: Apply Homebrew shellenv immediately
      shell: |
        eval "$(/opt/homebrew/bin/brew shellenv)"
        which brew
      register: which_brew
      changed_when: false
    - debug: msg="{{ which_brew.stdout }}"
    - debug: msg="{{ which_brew.stderr }}"
  when: which_brew.rc != 0
