---
- include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"
  when: ansible_facts['os_family'] | lower in ['debian', 'redhat']

- name: Run brew bundle
  ansible.builtin.command:
    cmd: brew bundle install --file {{ brewfile }}
  vars:
    brewfile: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_facts['env'].HOME + '/.config', true) }}/homebrew/Brewfile"
  environment:
    PATH: "/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:{{ ansible_facts['env'].PATH }}"
    HOMEBREW_NO_ANALYTICS: "1"
  register: brew_bundle
  changed_when: "'Installing' in brew_bundle.stdout or 'Upgrading' in brew_bundle.stdout"
  tags:
    - tools

- name: Install python
  ansible.builtin.command: uv python install
  args:
    creates: "{{ ansible_facts['env'].HOME }}/.local/share/uv/python/*/"
