---
- name: copr
  become: true
  community.general.copr:
    name: "{{item}}"
  loop:
    - agriffis/neovim-nightly
    - atim/bandwhich
    - atim/bottom
    - atim/lazydocker
    - atim/lazygit
    - atim/starship
    - errornointernet/packages
    - wezfurlong/wezterm-nightly

- name: Add 1Password RPM repository to DNF
  ansible.builtin.yum_repository:
    name: "1password"
    description: "1Password Stable Channel"
    baseurl: "https://downloads.1password.com/linux/rpm/stable/$basearch"
    gpgcheck: yes
    gpgkey: "https://downloads.1password.com/linux/keys/1password.asc"
    enabled: yes
  become: true

- name: install {{ packages | sort | join(', ')}}
  become: true
  vars:
    packages:
      - '@Development Tools'
      - '@Multimedia'
      - postgresql
      - procps-ng
  package:
    name: "{{ packages }}"
