---
- name: Install direnv
  ansible.builtin.package:
    name: direnv

- name: Ensure direnv is sourced
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    search_string: "direnv hook fish | source"
    line: "direnv hook fish | source"
