---
- name: Install fzf
  ansible.builtin.apt:
    name: fzf
  when: ansible_os_family == 'Debian'

- name: Install fzf
  community.general.homebrew:
    name: fzf
  when: ansible_os_family == 'Darwin'

- name: Ensure fzf is sourced
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    search_string: "fzf --fish | source"
    line: "fzf --fish | source"
