---
- name: Install neovim
  community.general.homebrew:
    name: neovim

- name: Link neovim config
  file:
    src: "nvim"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
    force: yes

- name: Install neovim python venv
  ansible.builtin.shell: |
    uv venv ~/.venv.nvim --allow-existing
    uv pip install pynvim beancount
  args:
    executable: "{{ fish_path }}"
    creates: ~/.venv.nvim/pyvenv.cfg

- name: Install/Clean/Update the plugins
  ansible.builtin.command: nvim --headless "+Lazy! sync" +qa
