---
- name: install nvm
  ansible.builtin.shell: fisher install jorgebucaran/nvm
  args:
    executable: "{{ fish_path }}"
    creates: "{{ ansible_env.HOME }}/.config/fish/functions/nvm.fish"

- name: Install NodeJS
  ansible.builtin.shell: nvm install lts
  args:
    executable: "{{ fish_path }}"
