---
- name: Install fish
  community.general.homebrew:
    name: fish # install via brew on linux so brew completions are automatically added

- name: Link fish config
  file:
    src: "{{ checkout_dir }}/config/fish"
    dest: "{{ ansible_env.HOME }}/.config/fish"
    state: link
    force: yes

- name: Get the fish binary path
  shell: PATH=/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:$PATH command -v fish
  register: fish_path
  changed_when: false
  become: false

- name: Add fish to /etc/shells
  become: true
  lineinfile:
    path: /etc/shells
    line: "{{ fish_path.stdout }}"

- name: Set fish as default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish_path.stdout }}"

- name: Install fisher
  ansible.builtin.shell: |
    curl -fsSL git.io/fisher | source
    fisher install jorgebucaran/fisher
    fisher update
  args:
    executable: "{{ fish_path.stdout }}"
    creates: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"

- name: Install zoxide
  ansible.builtin.apt:
    name: zoxide
  when: ansible_os_family == 'Debian'

- name: Install zoxide
  community.general.homebrew:
    name: zoxide
  when: ansible_os_family == 'Darwin'

- name: Ensure zoxide is sourced
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    search_string: "zoxide init fish | source"
    line: "zoxide init fish | source"

- name: Install starship
  community.general.homebrew:
    name: starship

- name: Ensure starship is sourced
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    search_string: "eval (starship init fish)"
    line: "eval (starship init fish)"

- name: Install direnv
  ansible.builtin.apt:
    name: direnv
  when: ansible_os_family == 'Debian'

- name: Install direnv
  community.general.homebrew:
    name: direnv
  when: ansible_os_family == 'Darwin'

- name: Ensure direnv is sourced
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    search_string: "direnv hook fish | source"
    line: "direnv hook fish | source"

- name: Link direnv config
  file:
    src: "{{ checkout_dir }}/config/direnv"
    dest: "{{ ansible_env.HOME }}/.config/direnv"
    state: link
    force: yes

