---
- name: Install starship
  community.general.homebrew:
    name: starship

- name: Link starship config
  file:
    src: "starship.toml"
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
    state: link
    force: yes

- name: Ensure starship is sourced
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    search_string: "eval (starship init fish)"
    line: "eval (starship init fish)"
