---
- name: Add WezTerm GPG key
  ansible.builtin.get_url:
    url: https://apt.fury.io/wez/gpg.key
    dest: /etc/apt/keyrings/wezterm-fury.gpg
    mode: '0644'
  when: ansible_os_family == 'Debian'

- name: Add WezTerm repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *'
    state: present
  when: ansible_os_family == 'Debian'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install WezTerm
  ansible.builtin.apt:
    name: wezterm
  when: ansible_os_family == 'Debian'

- name: Install wezterm
  community.general.homebrew:
    name: wezterm
  when: ansible_os_family == 'Darwin'

- name: Link wezterm config
  file:
    src: "wezterm/"
    dest: "{{ ansible_env.HOME }}/.config/wezterm"
    state: link
    force: yes

