---
- name: Install zoxide
  ansible.builtin.apt:
    name: zoxide
  when: ansible_os_family == 'Debian'

- name: Install zoxide
  community.general.homebrew:
    name: zoxide
  when: ansible_os_family == 'Darwin'

- name: Ensure zoxide is sourced
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    search_string: "zoxide init fish | source"
    line: "zoxide init fish | source"
