
# tap repositories and their packages

tap homebrew/core
brew aom
brew argo
brew aribb24
brew assimp
brew autoconf
brew automake
brew awk
brew awscli
brew bash
brew bat
brew bat-extras
brew bdw-gc
brew boost
brew borgmatic
brew brotli
brew btop
brew c-ares
brew ca-certificates
brew cairo
brew cffi
brew cjson
brew cmake
brew cmocka
brew commitizen
brew coreutils
brew dav1d
brew dbus
brew direnv
brew docbook
brew docbook-xsl
brew docutils
brew double-conversion
brew exa
brew eza
brew fastfetch
brew fd
brew ffmpeg
brew fish
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fzf
brew fzy
brew gawk
brew gcc
brew gd
brew gdbm
brew gdk-pixbuf
brew gdu
brew gettext
brew gh
brew ghostscript
brew giflib
brew git
brew git-delta
brew glab
brew glib
brew glow
brew gmp
brew gnu-getopt
brew gnu-sed
brew gnu-tar
brew gnupg
brew gnuplot
brew gnutls
brew gobject-introspection
brew gpgme
brew graphite2
brew graphviz
brew grep
brew grip
brew gsasl
brew gts
brew guile
brew harfbuzz
brew helix
brew helm
brew highway
brew hledger
brew httpie
brew hunspell
brew hwloc
brew hyperfine
brew icu4c
brew imagemagick
brew imath
brew isl
brew jansson
brew jasper
brew jbig2dec
brew jpeg
brew jpeg-turbo
brew jpeg-xl
brew jq
brew just
brew k9s
brew krb5
brew lame
brew lazydocker
brew lazygit
brew ledger
brew leptonica
brew less
brew libarchive
brew libass
brew libassuan
brew libavif
brew libb2
brew libbluray
brew libcerf
brew libde265
brew libevent
brew libffi
brew libgccjit
brew libgcrypt
brew libgit2
brew libgpg-error
brew libheif
brew libidn
brew libidn2
brew libksba
brew liblqr
brew libmagic
brew libmicrohttpd
brew libmng
brew libmpc
brew libnghttp2
brew libogg
brew libomp
brew libpng
brew libpq
brew libpthread-stubs
brew libraw
brew librist
brew librsvg
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh
brew libssh2
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunibreak
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxml2
brew libxrender
brew libyaml
brew little-cms2
brew llvm
brew lpeg
brew lua
brew luajit
brew luajit-openresty
brew luarocks
brew luv
brew lz4
brew lzo
brew m4
brew mailutils
brew make
brew mas
brew mbedtls
brew md4c
brew mpdecimal
brew mpfr
brew mpg123
brew mr
brew msgpack
brew ncurses
brew neofetch
brew neovide
brew neovim --HEAD
brew netpbm
brew nettle
brew npth
brew numpy
brew nushell
brew oniguruma
brew openblas
brew opencore-amr
brew openexr
brew openjpeg
brew openldap
brew openssl@1.1
brew openssl@3
brew openvino
brew opus
brew p11-kit
brew pandoc
brew pango
brew pcre
brew pcre2
brew pinentry
brew pipx
brew pixman
brew pkg-config
brew pngpaste
brew pre-commit
brew proselint
brew pspg
brew pugixml
brew pycparser
brew pygments
brew python-argcomplete
brew python-brotli
brew python-certifi
brew python-filelock
brew python-markdown
brew python-markupsafe
brew python-mutagen
brew python-packaging
brew python-setuptools
brew python-typing-extensions
brew python@3.10
brew python@3.11
brew python@3.12
brew python@3.9
brew pyyaml
brew qt
brew qt@5
brew ranger
brew rav1e
brew readline
brew reattach-to-user-namespace
brew ripgrep
brew rubberband
brew rust-analyzer
brew rustup-init
brew screenresolution
brew sdl2
brew shared-mime-info
brew shellcheck
brew shfmt
brew six
brew snappy
brew speex
brew sqlite
brew srt
brew starship
brew stow
brew svt-av1
brew task
brew tbb
brew tcl-tk
brew tealdeer
brew tesseract
brew texinfo
brew theora
brew timewarrior
brew tmux
brew tree-sitter
brew unbound
brew unibilium
brew unixodbc
brew utf8proc
brew uv
brew vcsh
brew virtualenv
brew webp
brew wget
brew x264
brew x265
brew xh
brew xmlto
brew xorgproto
brew xvid
brew xxhash
brew xz
brew youtube-dl
brew yq
brew yt-dlp
brew z3
brew zellij
brew zeromq
brew zimg
brew zlib
brew zoxide
brew zsh
brew zstd

tap homebrew/cask
cask 1password
cask 1password-cli
cask adobe-creative-cloud
cask alt-tab
cask amethyst
cask brave-browser
cask caffeine
cask docker
cask fantastical
cask fig
cask firefox
cask google-chrome
cask insomnia
cask intellij-idea-ce
cask iterm2
cask karabiner-elements
cask kitty
cask macfuse
cask miro
cask notion
cask obsidian
cask plex
cask postman
cask pycharm
cask raycast
cask rectangle
cask rectangle-pro
cask signal
cask slack
cask spotify
cask stats
cask steam
cask synology-drive
cask unnaturalscrollwheels
cask utm
cask visual-studio-code
cask vlc
cask warp

tap homebrew/bundle

tap homebrew/cask-drivers

tap homebrew/cask-fonts
cask font-monaspace

tap homebrew/cask-versions
cask wezterm-nightly

tap homebrew/services

tap arl/arl
brew gitmux

tap borgbackup/tap
brew borgbackup-fuse

tap d12frosted/emacs-plus
brew emacs-plus@29 --with-native-comp --with-imagemagick

tap danvergara/tools
brew dblab

tap derailed/k9s

tap hyde46/hoard

tap jdxcode/tap

tap jesseduffield/lazygit

tap koekeishiya/formulae
brew skhd
brew yabai

tap railwaycat/emacsmacport

tap rcmdnk/file
brew brew-file

tap tako8ki/tap
brew gobang

tap tnk-studio/tools
brew lazykube

tap withgraphite/tap
brew graphite

# Other Homebrew packages
brew python-distlib
brew python-platformdirs

# App Store applications
appstore 1287445660 Agenda (18.3.2)
appstore 1444383602 Goodnotes (6.3.6)
appstore 1136220934 Infuse (7.7)
appstore 409183694 Keynote (13.2)
appstore 360593530 Notability (14.7.3)
appstore 409203825 Numbers (13.2)
appstore 409201541 Pages (13.2)
appstore 1569600264 Pandan (1.16.0)
appstore 1596283165 rcmd (2.4.0)
appstore 425424353 The Unarchiver (4.3.6)
appstore 904280696 Things3 (3.20)
appstore 966085870 TickTick (5.0.60)
appstore 1449619230 Tim (8.9.0)
appstore 1607635845 Velja (1.16.4)
