- name: Ensure dev directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/dev/personal
    - ~/dev/alcemy
- name: Clone repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version | default('main') }}"
    update: no # Don't pull if repo exists
  loop:
    - repo: git@github.com:laermannjan/sysconf.git
      dest: ~/dev/personal/sysconf
    - repo: git@gitlab.com:jaerbert/conlife.git
      dest: ~/dev/personal/conlife
    - repo: git@lab.com:alcemy/cement/prism_ada.git
      dest: ~/dev/alcemy/prism_ada
    - repo: git@lab.com:alcemy/cement/prism_charles.git
      dest: ~/dev/alcemy/prism_charles
    - repo: git@lab.com:alcemy/cement/prism_raymond.git
      dest: ~/dev/alcemy/prism_raymond
    - repo: git@lab.com:alcemy/cement/prism_konrad.git
      dest: ~/dev/alcemy/prism_konrad
    - repo: git@lab.com:alcemy/cement/prism_john.git
      dest: ~/dev/alcemy/prism_john
