[tools]
python = "pipenv"
pipenv = "latest"
terraform = "latest"
golang = "latest"
lua = "latest"
ruby = "latest"
nodejs = "18"
pdm = "latest"

[settings]
experimental = true

[alias.python]
pipenv = "3.9.5"
