---
- name: Find dotfiles in {{ config_source }}
  find:
    paths: "{{ config_source }}"
    recurse: no
    file_type: any
    hidden: yes
  register: dotfiles

- name: Ensure {{ config_target }} exists
  file:
    path: "{{ config_target }}"
    state: directory
    mode: "0700"

- name: Linking dotfiles from {{ config_source }} -> {{ config_target }}
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ config_target }}/{{ item.path | basename }}"
    state: link
    force: yes
  loop: "{{ dotfiles.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
