- name: Install Command Line Tools
  import_role:
    name: elliotweiser.osx-command-line-tools
- name: Check if Rosetta 2 is installed
  command: arch -x86_64 true # checks if x86_64 code can be run on this machine
  register: rosetta_check
  ignore_errors: true
  changed_when: false
- name: Install Rosetta 2
  when: rosetta_check.failed
  command: /usr/sbin/softwareupdate --install-rosetta --agree-to-license
  become: true
  register: rosetta_install
  changed_when: rosetta_install.rc == 0
  failed_when:
    - rosetta_install.rc != 0
    - not 'Rosetta is already installed' in rosetta_install.stderr
- name: Configure macOS settings
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop:
    - {domain: NSGlobalDomain, key: KeyRepeat, type: int, value: 2}
    - {domain: NSGlobalDomain, key: InitialKeyRepeat, type: int, value: 15}
