
# tap repositories and their packages

tap homebrew/core
brew aom
brew asdf
brew autoconf
brew automake
brew awk
brew awscli
brew bash
brew bat
brew bdw-gc
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew cmake
brew coreutils
brew docbook
brew docbook-xsl
brew exa
brew fd
brew fish
brew fontconfig
brew freetype
brew fribidi
brew fzf
brew gcc
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghostscript
brew giflib
brew glib
brew gmp
brew gnu-getopt
brew gnu-sed
brew gnu-tar
brew gnutls
brew gobject-introspection
brew graphite2
brew graphviz
brew gts
brew guile
brew harfbuzz
brew icu4c
brew imagemagick
brew imath
brew isl
brew jansson
brew jasper
brew jbig2dec
brew jpeg
brew jpeg-xl
brew libavif
brew libde265
brew libevent
brew libffi
brew libheif
brew libidn
brew libidn2
brew liblqr
brew libmagic
brew libmpc
brew libnghttp2
brew libomp
brew libpng
brew libpthread-stubs
brew libraw
brew librsvg
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libuv
brew libvmaf
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew luajit-openresty
brew luv
brew lzo
brew m4
brew make
brew mas
brew mpdecimal
brew mpfr
brew msgpack
brew ncurses
brew neovim
brew netpbm
brew nettle
brew node
brew openexr
brew openjpeg
brew openssl@1.1
brew openssl@3
brew p11-kit
brew pango
brew pcre
brew pcre2
brew pixman
brew pkg-config
brew pngpaste
brew python@3.9
brew readline
brew ripgrep
brew rust-analyzer
brew rustup-init
brew shared-mime-info
brew shellcheck
brew six
brew sqlite
brew starship
brew tcl-tk
brew texinfo
brew tree-sitter
brew unbound
brew unibilium
brew unixodbc
brew webp
brew x265
brew xmlto
brew xorgproto
brew xz
brew zlib
brew zoxide
brew zsh
brew zstd

tap homebrew/cask-fonts

tap homebrew/cask
cask 1password
cask 1password-cli
cask alfred
cask brave-browser
cask docker
cask fantastical
cask firefox
cask iterm2
cask signal
cask slack
cask spotify
cask unnaturalscrollwheels
cask visual-studio-code

tap d12frosted/emacs-plus
brew emacs-plus@28 --with-xwidgets --with-imagemagick

tap hyde46/hoard

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 682658836   GarageBand  (10.4.5)
appstore 408981434   iMovie      (10.3.1)
appstore 409183694   Keynote     (11.2)
appstore 441258766   Magnet      (2.8.0)
appstore 409203825   Numbers     (11.2)
appstore 409201541   Pages       (11.2)
