
# tap repositories and their packages

tap homebrew/core
brew aom
brew asdf
brew autoconf
brew automake
brew awk
brew awscli
brew bash
brew bat
brew bdw-gc
brew boost
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew cjson
brew cmake
brew cmocka
brew coreutils
brew dav1d
brew docbook
brew docbook-xsl
brew exa
brew fd
brew ffmpeg
brew fish
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fzf
brew fzy
brew gcc
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew gh
brew ghostscript
brew giflib
brew git
brew git-delta
brew glab
brew glib
brew gmp
brew gnu-getopt
brew gnu-sed
brew gnu-tar
brew gnupg
brew gnuplot
brew gnutls
brew gobject-introspection
brew graphite2
brew graphviz
brew grip
brew gts
brew guile
brew harfbuzz
brew helix
brew helm
brew highway
brew hledger
brew icu4c
brew imagemagick
brew imath
brew isl
brew jansson
brew jasper
brew jbig2dec
brew jpeg
brew jpeg-turbo
brew jpeg-xl
brew lame
brew lazygit
brew ledger
brew leptonica
brew less
brew libarchive
brew libass
brew libassuan
brew libavif
brew libb2
brew libbluray
brew libcerf
brew libde265
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libheif
brew libidn
brew libidn2
brew libksba
brew liblqr
brew libmagic
brew libmpc
brew libnghttp2
brew libogg
brew libomp
brew libpng
brew libpthread-stubs
brew libraw
brew librist
brew librsvg
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew lua
brew luajit
brew luajit-openresty
brew luv
brew lz4
brew lzo
brew m4
brew make
brew mas
brew mbedtls
brew mpdecimal
brew mpfr
brew mr
brew msgpack
brew ncurses
brew neovide
brew neovim
brew netpbm
brew nettle
brew node
brew npth
brew opencore-amr
brew openexr
brew openjpeg
brew openssl@1.1
brew openssl@3
brew opus
brew p11-kit
brew pandoc
brew pango
brew pcre
brew pcre2
brew pinentry
brew pixman
brew pkg-config
brew pngpaste
brew proselint
brew python@3.10
brew python@3.9
brew qt@5
brew rav1e
brew readline
brew ripgrep
brew rubberband
brew rust-analyzer
brew rustup-init
brew sdl2
brew shared-mime-info
brew shellcheck
brew shfmt
brew six
brew snappy
brew speex
brew sqlite
brew srt
brew starship
brew stow
brew tcl-tk
brew tealdeer
brew tesseract
brew texinfo
brew theora
brew tmux
brew tree-sitter
brew unbound
brew unibilium
brew unixodbc
brew utf8proc
brew vcsh
brew webp
brew wget
brew x264
brew x265
brew xmlto
brew xorgproto
brew xvid
brew xz
brew youtube-dl
brew zeromq
brew zimg
brew zlib
brew zoxide
brew zsh
brew zstd

tap homebrew/cask-drivers
cask canon-eos-webcam-utility
cask synology-drive

tap homebrew/cask-fonts

tap homebrew/services

tap homebrew/cask
cask 1password
cask 1password-cli
cask alacritty
cask alfred
cask alt-tab
cask amethyst
cask balenaetcher
cask beekeeper-studio
cask brave-browser
cask cardhop
cask contexts
cask devtoys
cask docker
cask fantastical
cask fig
cask firefox
cask insomnia
cask intellij-idea-ce
cask iterm2
cask karabiner-elements
cask kitty
cask librewolf
cask miro
cask monitorcontrol
cask notion
cask obs
cask plex
cask postico
cask pycharm
cask rectangle
cask signal
cask slack
cask spotify
cask stats
cask steam
cask ubersicht
cask unnaturalscrollwheels
cask visual-studio-code
cask vlc

tap d12frosted/emacs-plus
brew emacs-plus@28 --with-xwidgets --with-imagemagick

tap hyde46/hoard

tap jesseduffield/lazygit

tap koekeishiya/formulae
brew skhd

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 1287445660  Agenda       (16.0)
appstore 1236045954  Canary Mail  (3.69)
appstore 682658836   GarageBand   (10.4.7)
appstore 1444383602  GoodNotes    (5.9.51)
appstore 408981434   iMovie       (10.3.5)
appstore 1136220934  Infuse       (7.4.7)
appstore 409183694   Keynote      (12.2)
appstore 441258766   Magnet       (2.10.0)
appstore 360593530   Notability   (11.7.7)
appstore 409203825   Numbers      (12.2)
appstore 409201541   Pages        (12.2)
appstore 1569600264  Pandan       (1.13.0)
appstore 1596283165  rcmd         (2.3.1)
appstore 1596706466  Speediness   (1.5.0)
appstore 1312926037  stoic.       (2022.56)
appstore 904280696   Things       (3.16.1)
appstore 1607635845  Velja        (1.12.1)
appstore 1601814648  Volum        (1.2.2)
