---
- include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family in ['Darwin', 'Debian']

- name: Link git config
  file:
    src: "{{ checkout_dir }}/config/git"
    dest: "{{ ansible_env.HOME }}/.config/git"
    state: link
    force: yes

- name: Install lazygit
  community.general.homebrew:
    name: lazygit

- name: Link lazygit config
  file:
    src: "{{ checkout_dir }}/config/lazygit"
    dest: "{{ ansible_env.HOME }}/.config/lazygit"
    state: link
    force: yes

- name: Install delta
  community.general.homebrew:
    name: git-delta
