#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# spaces
yabai -m space 1 --label mail
yabai -m space 2 --label code
yabai -m space 3 --label web
yabai -m space 4 --label notes
yabai -m space 5 --label media
yabai -m space 6 --label social
yabai -m space 7 --label games

# window rules
yabai -m rule --add app="^(Mail|Canary Mail)$" space=mail
yabai -m rule --add app="^(Safari|Brave Browser|Firefox|Google Chrome)$" space=web
yabai -m rule --add app="^(Notes|Notability|GoodNotes 5)$" space=notes
yabai -m rule --add app="^(PyCharm|Visual Studio Code|Emacs)$" space=re
yabai -m rule --add app="^Transmission$" space=media
yabai -m rule --add app="^(Spotify|Youtube Music|Plex)$" space=media
yabai -m rule --add app="^(Signal|Slack|Discord)$" space=social grid=1:1:0:0:1:1 manage=off
yabai -m rule --add app="^Steam$" space=games manage=off
yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility)$" manage=off
yabai -m rule --add app="^(mpv|VLC)$" manage=off border=off sticky=on layer=above opacity=1.0 grid=8:8:6:0:2:2

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config window_border_radius         12
yabai -m config window_border_blur           on
yabai -m config window_border_hidpi          on
yabai -m config window_animation_duration   0.25
# yabai -m config active_window_border_color   0xff775759
# yabai -m config normal_window_border_color   0xff555555
# yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config active_window_border_color   0xBF775759
yabai -m config normal_window_border_color   0x7f353535
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  4
yabai -m config bottom_padding               4
yabai -m config left_padding                 4
yabai -m config right_padding                4
yabai -m config window_gap                   4

echo "yabai configuration loaded.."
