#!/usr/bin/env bash

set -e

SYSCONF_DIR="${HOME}/sysconf"

if [[ -t 1 ]]; then
    tty_escape() { printf "\033[%sm" "$1"; }
else
    tty_escape() { :; }
fi
tty_mkbold() { tty_escape "1;$1"; }
tty_underline="$(tty_escape "4;39")"
tty_blue="$(tty_mkbold 34)"
tty_red="$(tty_mkbold 31)"
tty_bold="$(tty_mkbold 39)"
tty_reset="$(tty_escape 0)"

ohai() {
    printf "${tty_blue}==>${tty_bold} %s${tty_reset}\n" "$1"
}

have() {
    command -v "$1" &>/dev/null
}

install() {
    [ $(uname) = "Darwin" ] && brew install "$1"
    have apt && sudo apt install -y "$1"
    have dnf && sudo dnf install -y "$1"
    have pacman && sudo pacman -Syu --no-confirm "$1"
}

if [ $(uname) = "Darwin" ] && ! have brew; then
    ohai "ensuring brew is installed, available and up to date"
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    export PATH="/opt/homebrew/bin:${PATH}"
fi

ohai "ensuring ansible is installed"
have ansible || install ansible

ohai "ensuring ansible collections are installed"
ansible-galaxy collection list | grep community.general || ansible-galaxy collection install community.general
ansible-galaxy collection list | grep geerlingguy.mac || ansible-galaxy collection install geerlingguy.mac

if [[ ! -d "${SYSCONF_DIR}" ]]; then
    ohai "cloning sysconf repo to ${SYSCONF_DIR}"
    install git-lfs
    git clone https://github.com/laermannjan/sysconf.git "${SYSCONF_DIR}"
    git -C "${SYSCONF_DIR}" remote set-url origin git@github.com:laermannjan/sysconf.git
    git -C "${SYSCONF_DIR}" lfs pull
fi

ohai "running ansible playbook"
ansible-playbook ~/sysconf/ansible/playbook.yml "$@"

ohai "Done. Invoking fish shell. You should probably reboot now."
exec fish
