#!/usr/bin/env bash

set -euxo pipefail

SYSCONF_DIR="${HOME}/sysconf"
SYSCONF_REPO_HTTPS="https://github.com/laermannjan/sysconf.git"
SYSCONF_REPO_SSH="git@github.com:laermannjan/sysconf.git"

if [[ -t 1 ]]; then
    tty_escape() { printf "\033[%sm" "$1"; }
else
    tty_escape() { :; }
fi
tty_mkbold() { tty_escape "1;$1"; }
tty_underline="$(tty_escape "4;39")"
tty_blue="$(tty_mkbold 34)"
tty_green="$(tty_mkbold 32)"
tty_yellow="$(tty_mkbold 33)"
tty_cyan="$(tty_mkbold 36)"
tty_red="$(tty_mkbold 31)"
tty_bold="$(tty_mkbold 39)"
tty_reset="$(tty_escape 0)"

ohai() {
    printf "${tty_yellow}[ ... ]${tty_bold} %s${tty_reset}\n" "$1"
}

error() {
    printf "${tty_red}[ ### ]${tty_bold} %s${tty_reset}\n" "$1"
}

have() {
    command -v "$1" &>/dev/null
}

install() {
    [ $(uname) = "Darwin" ] && brew install "$1"
    have apt && sudo apt install -y "$1"
    have dnf && sudo dnf install -y "$1"
    have pacman && sudo pacman -Syu --no-confirm "$1"
}

ensure() {
    ohai "ensuring $1 is installed"
    have "$1" || install "$1"
}

if [ $(uname) = "Darwin" ] && ! have brew; then
    ohai "ensuring brew is installed, available and up to date"
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    export PATH="/opt/homebrew/bin:${PATH}"
fi

ensure ansible

ohai "ensuring ansible collections are installed"
ansible-galaxy collection list | grep community.general || ansible-galaxy collection install community.general
ansible-galaxy collection list | grep geerlingguy.mac || ansible-galaxy collection install geerlingguy.mac

if [[ ! -d "${SYSCONF_DIR}" ]]; then
    ensure git-lfs
    ohai "cloning sysconf repo to ${SYSCONF_DIR}"
    git clone ${SYSCONF_REPO_HTTPS} "${SYSCONF_DIR}"
    # make ssh the primary, keep https so we can fetch updates before ssh keys are installed
    git -C "${SYSCONF_DIR}" remote set-url --push origin "${SYSCONF_REPO_SSH}"
fi

pushd "${SYSCONF_DIR}"

git fetch origin
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse @{u})
BASE=$(git merge-base @ @{u})

if [[ $REMOTE != $BASE ]]; then
    error "New commits on remote. You might want to 'git pull --rebase && git lfs pull'\nGiving you 3 seconds to ^C"
    sleep 3
fi

ohai "running ansible playbook"
ansible-playbook ansible/playbook.yml "$@"

popd

ohai "Done. Invoking fish shell. You should probably reboot now."
exec fish
