#!/usr/bin/env bash

set -e

function have {
    command -v "$1" &>/dev/null
}

for dir in "${HOME}/.local/bin" "/opt/homebrew/bin" "/home/linuxbrew/.linuxbrew/bin"; do
    [ -d "$dir" ] && [[ ":$PATH:" != *":$dir:"* ]] && export PATH="$dir:$PATH"
done

[ ! -d "${HOME}/sysconf" ] && [ ! -d "${HOME}/sysconf/.git" ] && echo "cloning sysconf repo to ~/sysconf" && git clone https://github.com/laermannjan/sysconf.git ~/sysconf && pushd ~/sysconf && git remote set-url origin git@github.com:laermannjan/sysconf.git && popd

have uv || curl -LsSf https://astral.sh/uv/install.sh | sh && source "${HOME}/.local/bin/env"
# uv tool install doesn't put all the executables on the path, so I'm linking them myself https://github.com/astral-sh/uv/issues/6314#issuecomment-2510284936
have ansible || uv tool install ansible && find "$(uv tool dir)/ansible/bin" -mindepth 1 -maxdepth 1 -type f -perm -u=x -exec ln -f -s {} ~/.local/bin/ \;

pushd ~/sysconf/ansible
ansible-galaxy install -r requirements.yml
ansible-playbook playbook.yml --ask-vault-pass
popd

have brew && brew update
exec fish
echo "Done. You should reboot now."
