---
- hosts: localhost
  vars_prompt:
    # instead of -K/--ask-become-pass: geerlingguy.mac.homebrew uses this as
    # become password and passes it to sudo_password for cask post-install scripts
    - name: ansible_become_password
      prompt: sudo password
      private: yes

  roles:
    - {role: ssh, tags: ['ssh']}
    - {role: system, tags: ['system']}
    - {role: dotfiles, tags: ['dotfiles']}
    - {role: shell, tags: ['shell']}
    - {role: packages, tags: ['packages']}
    - {role: fonts, tags: ['fonts']}
