- hosts: localhost
  vars:
    xdg_config_home: "~/.config"
  pre_tasks:
    - name: Get repo checkout directory
      ansible.builtin.set_fact:
        checkout_path: "{{ playbook_dir | dirname }}"
  roles:
    - {role: system, tags: ['system']}
    - {role: packages, tags: ['packages']}
    - {role: shell, tags: ['shell']}
    - {role: ssh, tags: ['ssh']}
    - {role: config, tags: ['config']}
