complete --command mergid --short-option b --long-option lang-base   --require-parameter --description "Language code for base file"
complete --command mergid --short-option m --long-option lang-merge  --require-parameter --description "Language code for merge file"
complete --command mergid --short-option d --long-option delay       --require-parameter --description "Delay merge audio by N seconds"
complete --command mergid --short-option S --long-option no-sync     --description "Disable auto audio sync"
complete --command mergid --short-option o --long-option output      --require-parameter --description "Output filename"
complete --command mergid --short-option h --long-option help        --description "Show help"
