complete --command savid --short-option r --long-option referer  --require-parameter --description "Referer URL"
complete --command savid --short-option c --long-option cookie   --require-parameter --description "Cookie header string"
complete --command savid --short-option t --long-option title    --require-parameter --description "Episode title"
complete --command savid --short-option s --long-option show     --require-parameter --description "Show name"
complete --command savid --short-option y --long-option year     --require-parameter --description "Year / season"
complete --command savid --short-option e --long-option episode  --require-parameter --description "Episode number"
complete --command savid --short-option a --long-option artist   --require-parameter --description "Artist name"
complete --command savid --short-option f --long-option force    --description "Ignore yt-dlp cache (re-download)"
complete --command savid --short-option T --long-option no-artist-title --description "Don't prefix title tag with artist"
complete --command savid --short-option h --long-option help     --description "Show help"
