{ ... }:
{
  import = [
    ./cmp.nix
    ./colorscheme.nix
    ./comment.nix
    ./dap.nix
    ./diffview.nix
    ./direnv.nix
    ./git.nix
    ./headlines.nix
    ./hmts.nix
    ./indent-blankline.nix
    ./keymaps.nix
    ./lazygit.nix
    ./lsp.nix
    ./lualine.nix
    ./neotest.nix
    ./neotree.nix
    ./none-ls.nix
    ./nvim-autopair.nix
    ./options.nix
    ./smart-splits.nix
    ./telescope.nix
    ./todo-comments.nix
    ./treesitter.nix
    ./trouble.nix
    ./which-key.nix
  ];
}
