---

- name: Ensure {{ font_dir }} exists
  file:
    path: "{{ font_dir }}"
    state: directory

- name: fonts
  unarchive:
    src: "{{ playbook_dir }}/roles/fonts/files/fonts.tar.xz.vault"
    dest: "{{ font_dir }}"
    decrypt: yes
    mode: '0644'

- name: udpate font cache
  command: fc-cache -vf
  when: ansible_os_family != 'Darwin'
