---

- name: fonts
  unarchive:
    src: "{{ playbook_dir }}/roles/fonts/files/fonts.tar.xz.vault"
    dest: "{{ ansible_env.HOME }}/{{ 'Library/Fonts' if ansible_os_family == 'Darwin' else '.local/share/fonts' }}"
    decrypt: yes
    mode: '0644'

- name: udpate font cache
  command: fc-cache -vf
  when: ansible_os_family != 'Darwin'
