[settings]
dotfiles.root = "~/sysconf"
dotfiles.default_mode = "symlink"
python.uv_venv_auto = "create|source"
activate_aggressive = true

[bootstrap.mise_shell_activate]
fish = "activate"

[dotfiles]
"~/.config/1password" = {}
"~/.config/direnv" = {}
"~/.config/fish" = {}
"~/.config/ghostty" = {}
"~/.config/git" = {}
"~/.config/homebrew" = {}
"~/.config/karabiner" = {}
"~/.config/lazygit" = {}
"~/.config/linearmouse" = {}
"~/.config/mise/config.toml" = {}
"~/.config/mise/config.macos.toml" = {}
"~/.config/mise/miserc.toml" = {}
"~/.config/nvim" = {}
"~/.config/starship.toml" = {}
"~/.config/wezterm" = {}
"~/.config/yt-dlp" = {}
"~/.ssh/config" = {}

[tools]
python = "latest"
uv = "latest"
ty = "latest"
ruff = "latest"
go = "latest"
ruby = "latest"
node = "lts"
rust = "latest"
zig = "latest"

1password = "latest"
bat = "latest"
bottom = "latest"
claude = "latest"
curlie = "latest"
dust = "latest"
grex = "latest"
gum = "latest"
jq = "latest"
opencode = "latest"
pre-commit = "latest"
ripgrep = "latest"
starship = "latest"
tealdeer = "latest"
tmux = "latest"
typst = "latest"
usage = "latest"
zoxide = "latest"
doggo = "latest"
ffmpeg = "latest"
imagemagick = "latest"
lazygit = "latest"
lazydocker = "latest"
delta = "latest"
tree-sitter = "latest"
hk = "latest"
neovim = "nightly"
yt-dlp = "latest"
eza = "latest"

[env]
EDITOR = "nvim"
VISUAL = "nvim"
PAGER = "less"
LESS = "-R -F -X --mouse"
